# Generated by Django 4.2.11 on 2024-04-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
